baseURL = "https://helmholtz-imaging.github.io/helmholtz-imaging-solutions"
languageCode = "en-us"
title = "Helmholtz Imaging Solutions"
theme = "hugo-theme-helmholtz-imaging-workshop"
[markup.goldmark.renderer]
unsafe= true
canonifyURLs= true
[params.mermaid]
enable = true
[params.plantuml]
enable = true
[markup]
  [markup.highlight]
      guessSyntax = "false"